### ISSUE TITLE
Render custom plot: feature request?

### ISSUE THREAD

**Issue by JudithBernett** [datavzrd/datavzrd#789]
Hello :) I have tried out your library to generate a report for the results of a workflow, and I really like it! 
Is it possible to include custom files? I have, e.g., a custom plot (SVG but could also be anything else) visualizing the critical difference between cross-validation runs, which looks like this 

<img width="736" alt="Bildschirmfoto 2024-10-04 um 11 50 21" src="https://github.com/user-attachments/assets/6ff3de26-dd96-4dd4-a1e1-404ae13b486f">

I think it would take some time to redo this plot with vega-lite because I don't really know the library, so I'd like to just include it as an extra view. 

Best,
Judith

**Comment by fxwiegand** [comment]
Hi Judith! 

great to hear you like Datavzrd! I did try around a bit and found a solution that will eventually work using the `render-html` option:

To your config add a dataset and view like this and replace the `path/to/embed_img.js` and `path/to/plot_path.csv` with the actual paths:

```yaml
datasets:
  plot_path:
    path: "path/to/plot_path.csv"
views:
  critical_diff_plot:
    dataset: plot_path
    render-html:
      script-path: "path/to/embed_img.js"
```

Your dataset should then look like this (replace the path to your actual svg):

```csv
path
/home/felixwiegand/Downloads/visualization.svg
```

Into the `path/to/embed_img.js` file simply paste this code:

```javascript
let filePath = data[0]["path"]
const img = document.createElement('img');
img.src = filePath; // Set the source to the PNG file path
img.alt = 'critical_diff_plot'; // Optional alt text for accessibility

// Optionally, set width or height
img.width = 300; // Change as needed
img.height = 300; // Change as needed

// Insert the image into the canvas div
const canvasDiv = document.getElementById('canvas');
canvasDiv.appendChild(img);
```

I did have to do a tiny fix for this in #790 that should now be released. If you have datavzrd installed via mamba or you might have to wait a bit for it to be available as we currently face some packaging issues due to other new features. 

Otherwise I am sure ChatGPT will be able to convert the script that is creating your plot into Vega-lite specs fairly easily. 

Thanks again for giving datavzrd a try and hope I could help!

All the best,
Felix

**Comment by fxwiegand** [comment]
I also just did talk to @johanneskoester about a potential new feature looking like this that would highly simplify your use-case:

```yaml
views:
  critical_diff_plot:
    render-img:
      path: some.png
```

Also with something like `width` and `height` on the same level as `path`. I will try to implement this next week!

**Comment by JudithBernett** [comment]
Nice! Keep me updated! Until then, I'll try to get more into vega-lite :D

**Comment by fxwiegand** [comment]
> Nice! Keep me updated! Until then, I'll try to get more into vega-lite :D

Hi @JudithBernett 
just wanted to let you know this feature is now implemented and included in the latest release!
